name: Cleanup All Workflow Runs

permissions:
  actions: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */2 * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api repos/${GITHUB_REPOSITORY}/actions/runs --paginate --jq '.workflow_runs[].id' | \
          xargs -n1 -I {} gh api repos/${GITHUB_REPOSITORY}/actions/runs/{} -X DELETE --silent
        env:
          GH_TOKEN: ${{ github.token }}
