name: Cleanup Old Workflow Runs

permissions:
  actions: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */2 * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - run: |
          runs=$(gh api repos/${GITHUB_REPOSITORY}/actions/runs --paginate --jq '.workflow_runs[] | [.id, .created_at] | @tsv')
          deleted=0
          now=$(date +%s)
          while IFS=$'\t' read -r id created; do
            ts=$(date -d "$created" +%s)
            if (( now - ts > 172800 )); then
              gh api repos/${GITHUB_REPOSITORY}/actions/runs/$id -X DELETE --silent
              ((deleted++))
            fi
          done <<< "$runs"
          echo "Deleted $deleted runs"
        env:
          GH_TOKEN: ${{ github.token }}
