name: Cleanup Old Workflow Runs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */2 * *"

jobs:
  delete_logs:
    runs-on: ubuntu-latest

    steps:
      - name: Delete old workflow runs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          runs=$(gh api repos/${GITHUB_REPOSITORY}/actions/runs --paginate --jq '.workflow_runs[] | [.id, .created_at] | @tsv')
          while IFS=$'\t' read -r id date; do
            ts=$(date -d "$date" +%s)
            if (( ( $(date +%s) - ts ) > 172800 )); then
              gh api repos/${GITHUB_REPOSITORY}/actions/runs/$id -X DELETE
            fi
          done <<< "$runs"
